"""add_a2a_fields_in_agents_table

Revision ID: 545d3083200b
Revises: 07ac76cc090a
Create Date: 2025-04-30 17:35:31.573159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545d3083200b'
down_revision: Union[str, None] = '07ac76cc090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_card_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'agent_card_url')
    # ### end Alembic commands ###
